# Generated by Django 4.1.5 on 2023-01-14 16:09

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cycle_user_order_starting_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('starting_point', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('end_point', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='end_point',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.AddField(
            model_name='usercycle',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cycle'),
        ),
        migrations.AddField(
            model_name='usercycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
