# Generated by Django 4.1.5 on 2023-01-14 23:46

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request_usercycle_cycle_available_cycle_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='starting_point',
        ),
        migrations.AddField(
            model_name='request',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cycle'),
        ),
        migrations.AddField(
            model_name='request',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='current_location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
